### ISSUE TITLE
Feature Request Handling multiple Plot Folders

### ISSUE THREAD

**Issue by Pecadis** [chiafactory/plotorder#4]
Hi,

is there a way for the tool to handle multiple Plot Folders?
Something like the following pseudo-code

```
Read list of directories
current_directory = first directory of the list

when  current_directory has enough space for a plot
    download the plot into his directory
    else set current_directory to the next directory from the list
repeat
```

**Comment by trepca** [comment]
Hi! 
Great idea. We'll be adding this feature in the new version, written in Go for portability and network performance. 
You can track progress here: https://github.com/chiafactory/plotorder/tree/go

**Comment by trepca** [comment]
We now handle multiple plot folders, please check the latest version.
